### PR TITLE
Add `Equals` non-operator

### PR DESCRIPTION
**Pull request by l-monnier**
Here's the pull request as per our discussion for issue #17.

I let you see if the `Equals` name is fine for you and the location of the added code.

### CODE REVIEW

**Comment by l-monnier** [comment]
Note that I could also successfully implement `ElemOf` building on `Equals` and `(||)`. So it is possible to write:

```idris
hdec0 {p = (ElemOf [0, 15, 30, 45])} value
```
I'll make a pull request once this one is over, so if necessary, I can adapt in consequences.

I'm not 100% happy with the implementation I could come with (it's somehow a bit ugly and I'm sure there are more elegant ways to do it! but let's see this later).

**Comment by stefan-hoeck** [comment]
About `ElemOf`: There is already `Data.List.Elem`, as well as `Data.List.Quantifiers.Any`, so I don't think we need `ElemOf`.

**Comment by l-monnier** [comment]
I'm missing something here... When I try:

```idris
case hdec0 {p = (flip Elem) [0, 15, 30, 45]} val of
```

I get the following error:
`Can't find an implementation for HDec0 Bits8 (\y => Elem y [0, 15, 30, 45])`

where my record type has the same exact proof (which compiles). While my clumsy `ElemOf` works like a charm...

Also, note that `Elem` has the parameters reversed, so I guess it needs a `flip` which is not the most convenient.

**Comment by stefan-hoeck** [comment]
Yes, `HDec0` for `Elem` has not been implemented. I suggest you use `Data.List.Quantifiers.Any` because it is strictly more powerful than `Elem`:

```idris
module Any

import Data.Refined
import Data.List.Elem

%default total

0 ElemOf : List t -> t -> Type
ElemOf vs v = Any (Equal v) vs

Values : List Bits8
Values = [0,2,4,8,16]

inValues : (v : Bits8) -> Maybe0 (ElemOf Values v)
inValues v = hdec0 Values
```

Here's how to convert from this version of `ElemOf` to your version and back:

```idris
0 ElemOf' : List t -> t -> Type
ElemOf' []        = const Void
ElemOf' (x :: xs) = Equal x || ElemOf' xs

toElemOf : ElemOf vs v -> ElemOf' vs v
toElemOf (Here x)  = L (sym x)
toElemOf (There x) = R $ toElemOf x

fromElemOf : {vs : _} -> ElemOf' vs v -> ElemOf vs v
fromElemOf {vs = []}     x impossible
fromElemOf {vs = _ :: _} (L x) = Here (sym x)
fromElemOf {vs = _ :: _} (R x) = There $ fromElemOf x
```

And here's how to convert from `ElemOf` to `Elem`:

```idris
toElem : ElemOf vs v -> Elem v vs
toElem (Here Refl) = Here
toElem (There x)   = There $ toElem x
```

Note also, that in the code above I used `Equal` (from module `Builtin` in the prelude) directly, so I guess we don't even need the `Equals` alias from this PR.

Edit: Note that `Equals` might still be useful to help with type inference, because `Equal` and `(=)` describe (type-)heterogeneous equality, while `Equals` and `(===)` describe homogeneous equality.

**Comment by l-monnier** [comment]
Sorry for the delay in my answer, I unfortunately did not get sufficient time to dive into this recently.

It turns out that I indeed don't need `Equals` and that the `Equal` from the prelude is sufficient.

On a small note, my version of `ElemOf` needs to be implemented as follow with a non-empty list case:

```idris 
0 ElemOf' : List t -> t -> Type 
ElemOf' []        = const Void 
ElemOf' (x :: []) = Equal x 
ElemOf' (x :: xs) = Equal x || ElemOf' xs 
```

Otherwise, we always end up on the empty list which has type `(\value => Void)` for which `HDec0` has no implementation.

Then, on the confusing part, my code doesn't compile with `ElemOf` but works fine with `ElemOf'`.
I could nail it down to the below, without knowing why it behaves this way, while your example works perfectly fine...

```idris
0 ElemOf : List t -> t -> Type
ElemOf vs v = Any (Equal v) vs

Values : List Bits8
Values = [0,2,4,8,16]

record Rec where
  constructor MkRec
  rec : Bits8
  {auto 0 valid : ElemOf Values rec}
```

When I try `MkRec 2` then I get:

```idris
Error: When unifying:
    0
and:
    2
Mismatch between: 0 and 2.
```

As if I was not providing a `List`, but only `0`. I really don't get why I get this error, as `inValues` works fine (and then why it works perfectly fine with `ElemOf'` using `Equal` from the prelude).

**Pull request closed without merging**
